#!/bin/bash

# Script to insert moh data using id as region ID

python manage.py insert_geo_data --type moh --name 'MATHURATA' --region-id MOH-23001 --data-file ../submodules/gig-data/geo/moh/MOH-23001.json
python manage.py insert_geo_data --type moh --name 'WALAPANE' --region-id MOH-23002 --data-file ../submodules/gig-data/geo/moh/MOH-23002.json
python manage.py insert_geo_data --type moh --name 'HANGURANKETHA' --region-id MOH-23003 --data-file ../submodules/gig-data/geo/moh/MOH-23003.json
python manage.py insert_geo_data --type moh --name 'KOTHMALE' --region-id MOH-23004 --data-file ../submodules/gig-data/geo/moh/MOH-23004.json
python manage.py insert_geo_data --type moh --name 'AMBAGAMUWA' --region-id MOH-23005 --data-file ../submodules/gig-data/geo/moh/MOH-23005.json
python manage.py insert_geo_data --type moh --name 'KOTAGALA' --region-id MOH-23006 --data-file ../submodules/gig-data/geo/moh/MOH-23006.json
python manage.py insert_geo_data --type moh --name 'NAWATHISPANE' --region-id MOH-23007 --data-file ../submodules/gig-data/geo/moh/MOH-23007.json
python manage.py insert_geo_data --type moh --name 'NUWARA ELIYA' --region-id MOH-23008 --data-file ../submodules/gig-data/geo/moh/MOH-23008.json
python manage.py insert_geo_data --type moh --name 'NUWARA ELIYA MC' --region-id MOH-23009 --data-file ../submodules/gig-data/geo/moh/MOH-23009.json
python manage.py insert_geo_data --type moh --name 'RAGALA' --region-id MOH-23010 --data-file ../submodules/gig-data/geo/moh/MOH-23010.json
python manage.py insert_geo_data --type moh --name 'MASKELIYA' --region-id MOH-23011 --data-file ../submodules/gig-data/geo/moh/MOH-23011.json
python manage.py insert_geo_data --type moh --name 'BOGAWANTHALAWA' --region-id MOH-23012 --data-file ../submodules/gig-data/geo/moh/MOH-23012.json
python manage.py insert_geo_data --type moh --name 'LINDULA' --region-id MOH-23013 --data-file ../submodules/gig-data/geo/moh/MOH-23013.json
python manage.py insert_geo_data --type moh --name 'MATARA MC' --region-id MOH-32001 --data-file ../submodules/gig-data/geo/moh/MOH-32001.json
python manage.py insert_geo_data --type moh --name 'MATARA PS' --region-id MOH-32002 --data-file ../submodules/gig-data/geo/moh/MOH-32002.json
python manage.py insert_geo_data --type moh --name 'WELIGAMA' --region-id MOH-32003 --data-file ../submodules/gig-data/geo/moh/MOH-32003.json
python manage.py insert_geo_data --type moh --name 'PASGODA' --region-id MOH-32004 --data-file ../submodules/gig-data/geo/moh/MOH-32004.json
python manage.py insert_geo_data --type moh --name 'THIHAGODA' --region-id MOH-32005 --data-file ../submodules/gig-data/geo/moh/MOH-32005.json
python manage.py insert_geo_data --type moh --name 'KIRINDA PUHULWELLA' --region-id MOH-32006 --data-file ../submodules/gig-data/geo/moh/MOH-32006.json
python manage.py insert_geo_data --type moh --name 'MALIMBADA' --region-id MOH-32007 --data-file ../submodules/gig-data/geo/moh/MOH-32007.json
python manage.py insert_geo_data --type moh --name 'PITABEDDARA' --region-id MOH-32008 --data-file ../submodules/gig-data/geo/moh/MOH-32008.json
python manage.py insert_geo_data --type moh --name 'ATHURALIYA' --region-id MOH-32009 --data-file ../submodules/gig-data/geo/moh/MOH-32009.json
python manage.py insert_geo_data --type moh --name 'KOTAPOLA' --region-id MOH-32010 --data-file ../submodules/gig-data/geo/moh/MOH-32010.json
python manage.py insert_geo_data --type moh --name 'MULATIYANA' --region-id MOH-32011 --data-file ../submodules/gig-data/geo/moh/MOH-32011.json
python manage.py insert_geo_data --type moh --name 'HAKMANA' --region-id MOH-32012 --data-file ../submodules/gig-data/geo/moh/MOH-32012.json
python manage.py insert_geo_data --type moh --name 'KAMBURUPITIYA' --region-id MOH-32013 --data-file ../submodules/gig-data/geo/moh/MOH-32013.json
python manage.py insert_geo_data --type moh --name 'WELIPITIYA' --region-id MOH-32014 --data-file ../submodules/gig-data/geo/moh/MOH-32014.json
python manage.py insert_geo_data --type moh --name 'AKURESSA' --region-id MOH-32015 --data-file ../submodules/gig-data/geo/moh/MOH-32015.json
python manage.py insert_geo_data --type moh --name 'DEVINUWARA' --region-id MOH-32016 --data-file ../submodules/gig-data/geo/moh/MOH-32016.json
python manage.py insert_geo_data --type moh --name 'DICKWELLA' --region-id MOH-32017 --data-file ../submodules/gig-data/geo/moh/MOH-32017.json
python manage.py insert_geo_data --type moh --name 'DAMBULLA' --region-id MOH-22001 --data-file ../submodules/gig-data/geo/moh/MOH-22001.json
python manage.py insert_geo_data --type moh --name 'YATAWATTA' --region-id MOH-22002 --data-file ../submodules/gig-data/geo/moh/MOH-22002.json
python manage.py insert_geo_data --type moh --name 'AMBANGANGA KORALE' --region-id MOH-22003 --data-file ../submodules/gig-data/geo/moh/MOH-22003.json
python manage.py insert_geo_data --type moh --name 'NAULA' --region-id MOH-22004 --data-file ../submodules/gig-data/geo/moh/MOH-22004.json
python manage.py insert_geo_data --type moh --name 'PALLEPOLA' --region-id MOH-22005 --data-file ../submodules/gig-data/geo/moh/MOH-22005.json
python manage.py insert_geo_data --type moh --name 'RATTOTA' --region-id MOH-22006 --data-file ../submodules/gig-data/geo/moh/MOH-22006.json
python manage.py insert_geo_data --type moh --name 'GALEWELA' --region-id MOH-22007 --data-file ../submodules/gig-data/geo/moh/MOH-22007.json
python manage.py insert_geo_data --type moh --name 'LAGGALA-PALLEGAMA' --region-id MOH-22008 --data-file ../submodules/gig-data/geo/moh/MOH-22008.json
python manage.py insert_geo_data --type moh --name 'MATALE' --region-id MOH-22009 --data-file ../submodules/gig-data/geo/moh/MOH-22009.json
python manage.py insert_geo_data --type moh --name 'WILGAMUWA' --region-id MOH-22010 --data-file ../submodules/gig-data/geo/moh/MOH-22010.json
python manage.py insert_geo_data --type moh --name 'UKUWELA' --region-id MOH-22011 --data-file ../submodules/gig-data/geo/moh/MOH-22011.json
python manage.py insert_geo_data --type moh --name 'MENIKHINNA' --region-id MOH-21001 --data-file ../submodules/gig-data/geo/moh/MOH-21001.json
python manage.py insert_geo_data --type moh --name 'KUNDASALE' --region-id MOH-21002 --data-file ../submodules/gig-data/geo/moh/MOH-21002.json
python manage.py insert_geo_data --type moh --name 'KANDY FOUR GRAVETS & GANGAWATA KORALE' --region-id MOH-21003 --data-file ../submodules/gig-data/geo/moh/MOH-21003.json
python manage.py insert_geo_data --type moh --name 'PASBAGE KORALE' --region-id MOH-21004 --data-file ../submodules/gig-data/geo/moh/MOH-21004.json
python manage.py insert_geo_data --type moh --name 'UDUNUWARA' --region-id MOH-21005 --data-file ../submodules/gig-data/geo/moh/MOH-21005.json
python manage.py insert_geo_data --type moh --name 'BAMBARADENIYA' --region-id MOH-21006 --data-file ../submodules/gig-data/geo/moh/MOH-21006.json
python manage.py insert_geo_data --type moh --name 'UDAPALATHA' --region-id MOH-21007 --data-file ../submodules/gig-data/geo/moh/MOH-21007.json
python manage.py insert_geo_data --type moh --name 'DELTHOTA' --region-id MOH-21008 --data-file ../submodules/gig-data/geo/moh/MOH-21008.json
python manage.py insert_geo_data --type moh --name 'POOJAPITIYA' --region-id MOH-21009 --data-file ../submodules/gig-data/geo/moh/MOH-21009.json
python manage.py insert_geo_data --type moh --name 'HARISPATTUWA' --region-id MOH-21010 --data-file ../submodules/gig-data/geo/moh/MOH-21010.json
python manage.py insert_geo_data --type moh --name 'YATINUWARA' --region-id MOH-21011 --data-file ../submodules/gig-data/geo/moh/MOH-21011.json
python manage.py insert_geo_data --type moh --name 'GANGA IHALA KORALE' --region-id MOH-21012 --data-file ../submodules/gig-data/geo/moh/MOH-21012.json
python manage.py insert_geo_data --type moh --name 'DOLUWA' --region-id MOH-21013 --data-file ../submodules/gig-data/geo/moh/MOH-21013.json
python manage.py insert_geo_data --type moh --name 'THUMPANE' --region-id MOH-21014 --data-file ../submodules/gig-data/geo/moh/MOH-21014.json
python manage.py insert_geo_data --type moh --name 'HATHARALIYADDA' --region-id MOH-21015 --data-file ../submodules/gig-data/geo/moh/MOH-21015.json
python manage.py insert_geo_data --type moh --name 'PATHAHEWAHETA' --region-id MOH-21016 --data-file ../submodules/gig-data/geo/moh/MOH-21016.json
python manage.py insert_geo_data --type moh --name 'UDADUMBARA' --region-id MOH-21017 --data-file ../submodules/gig-data/geo/moh/MOH-21017.json
python manage.py insert_geo_data --type moh --name 'AKURANA' --region-id MOH-21018 --data-file ../submodules/gig-data/geo/moh/MOH-21018.json
python manage.py insert_geo_data --type moh --name 'MEDADUMBARA' --region-id MOH-21019 --data-file ../submodules/gig-data/geo/moh/MOH-21019.json
python manage.py insert_geo_data --type moh --name 'PANVILA' --region-id MOH-21020 --data-file ../submodules/gig-data/geo/moh/MOH-21020.json
python manage.py insert_geo_data --type moh --name 'PATHADUMBARA' --region-id MOH-21021 --data-file ../submodules/gig-data/geo/moh/MOH-21021.json
python manage.py insert_geo_data --type moh --name 'MINIPE' --region-id MOH-21022 --data-file ../submodules/gig-data/geo/moh/MOH-21022.json
python manage.py insert_geo_data --type moh --name 'KATUWANA' --region-id MOH-33001 --data-file ../submodules/gig-data/geo/moh/MOH-33001.json
python manage.py insert_geo_data --type moh --name 'TANGALLE' --region-id MOH-33002 --data-file ../submodules/gig-data/geo/moh/MOH-33002.json
python manage.py insert_geo_data --type moh --name 'AMBALANTOTA' --region-id MOH-33003 --data-file ../submodules/gig-data/geo/moh/MOH-33003.json
python manage.py insert_geo_data --type moh --name 'WEERAKETIYA' --region-id MOH-33004 --data-file ../submodules/gig-data/geo/moh/MOH-33004.json
python manage.py insert_geo_data --type moh --name 'ANGUNUKOLAPELES' --region-id MOH-33005 --data-file ../submodules/gig-data/geo/moh/MOH-33005.json
python manage.py insert_geo_data --type moh --name 'BELIATTA' --region-id MOH-33006 --data-file ../submodules/gig-data/geo/moh/MOH-33006.json
python manage.py insert_geo_data --type moh --name 'OKEWELA' --region-id MOH-33007 --data-file ../submodules/gig-data/geo/moh/MOH-33007.json
python manage.py insert_geo_data --type moh --name 'WALASMULLA' --region-id MOH-33008 --data-file ../submodules/gig-data/geo/moh/MOH-33008.json
python manage.py insert_geo_data --type moh --name 'HAMBANTOTA' --region-id MOH-33009 --data-file ../submodules/gig-data/geo/moh/MOH-33009.json
python manage.py insert_geo_data --type moh --name 'TISSAMAHARAMA' --region-id MOH-33010 --data-file ../submodules/gig-data/geo/moh/MOH-33010.json
python manage.py insert_geo_data --type moh --name 'LUNUGAMVEHERA' --region-id MOH-33011 --data-file ../submodules/gig-data/geo/moh/MOH-33011.json
python manage.py insert_geo_data --type moh --name 'SOORIYAWEWA' --region-id MOH-33012 --data-file ../submodules/gig-data/geo/moh/MOH-33012.json
python manage.py insert_geo_data --type moh --name 'IMADUWA' --region-id MOH-31001 --data-file ../submodules/gig-data/geo/moh/MOH-31001.json
python manage.py insert_geo_data --type moh --name 'KARANDENIYA' --region-id MOH-31002 --data-file ../submodules/gig-data/geo/moh/MOH-31002.json
python manage.py insert_geo_data --type moh --name 'BALAPITIYA' --region-id MOH-31003 --data-file ../submodules/gig-data/geo/moh/MOH-31003.json
python manage.py insert_geo_data --type moh --name 'NAGODA' --region-id MOH-31004 --data-file ../submodules/gig-data/geo/moh/MOH-31004.json
python manage.py insert_geo_data --type moh --name 'ELPITIYA' --region-id MOH-31005 --data-file ../submodules/gig-data/geo/moh/MOH-31005.json
python manage.py insert_geo_data --type moh --name 'HIKKADUWA' --region-id MOH-31006 --data-file ../submodules/gig-data/geo/moh/MOH-31006.json
python manage.py insert_geo_data --type moh --name 'RATHGAMA' --region-id MOH-31007 --data-file ../submodules/gig-data/geo/moh/MOH-31007.json
python manage.py insert_geo_data --type moh --name 'AKMEEMANA' --region-id MOH-31008 --data-file ../submodules/gig-data/geo/moh/MOH-31008.json
python manage.py insert_geo_data --type moh --name 'GONAPINUWALA' --region-id MOH-31009 --data-file ../submodules/gig-data/geo/moh/MOH-31009.json
python manage.py insert_geo_data --type moh --name 'AMBALANGODA' --region-id MOH-31010 --data-file ../submodules/gig-data/geo/moh/MOH-31010.json
python manage.py insert_geo_data --type moh --name 'BADDEGAMA' --region-id MOH-31011 --data-file ../submodules/gig-data/geo/moh/MOH-31011.json
python manage.py insert_geo_data --type moh --name 'BENTOTA' --region-id MOH-31012 --data-file ../submodules/gig-data/geo/moh/MOH-31012.json
python manage.py insert_geo_data --type moh --name 'BOPE-PODDALA' --region-id MOH-31013 --data-file ../submodules/gig-data/geo/moh/MOH-31013.json
python manage.py insert_geo_data --type moh --name 'HABARADUWA' --region-id MOH-31014 --data-file ../submodules/gig-data/geo/moh/MOH-31014.json
python manage.py insert_geo_data --type moh --name 'NELUWA' --region-id MOH-31015 --data-file ../submodules/gig-data/geo/moh/MOH-31015.json
python manage.py insert_geo_data --type moh --name 'NIYAGAMA' --region-id MOH-31016 --data-file ../submodules/gig-data/geo/moh/MOH-31016.json
python manage.py insert_geo_data --type moh --name 'THAWALAMA' --region-id MOH-31017 --data-file ../submodules/gig-data/geo/moh/MOH-31017.json
python manage.py insert_geo_data --type moh --name 'WELIVITIYA-DIVITHURA' --region-id MOH-31018 --data-file ../submodules/gig-data/geo/moh/MOH-31018.json
python manage.py insert_geo_data --type moh --name 'YAKKALAMULLA' --region-id MOH-31019 --data-file ../submodules/gig-data/geo/moh/MOH-31019.json
python manage.py insert_geo_data --type moh --name 'GALLE FOUR GRAVETS' --region-id MOH-31020 --data-file ../submodules/gig-data/geo/moh/MOH-31020.json
python manage.py insert_geo_data --type moh --name 'ALAYADIVEMBU' --region-id MOH-52001 --data-file ../submodules/gig-data/geo/moh/MOH-52001.json
python manage.py insert_geo_data --type moh --name 'AKKARAIPATTU' --region-id MOH-52002 --data-file ../submodules/gig-data/geo/moh/MOH-52002.json
python manage.py insert_geo_data --type moh --name 'KALNUMAI NORTH ( TAMIL DIV )' --region-id MOH-52003 --data-file ../submodules/gig-data/geo/moh/MOH-52003.json
python manage.py insert_geo_data --type moh --name 'IRAKKAMAM' --region-id MOH-52004 --data-file ../submodules/gig-data/geo/moh/MOH-52004.json
python manage.py insert_geo_data --type moh --name 'ADDACHCHENAI' --region-id MOH-52005 --data-file ../submodules/gig-data/geo/moh/MOH-52005.json
python manage.py insert_geo_data --type moh --name 'KALMUNAI SOUTH ( MUSLIM DIV )' --region-id MOH-52006 --data-file ../submodules/gig-data/geo/moh/MOH-52006.json
python manage.py insert_geo_data --type moh --name 'SAMMANTHURAI' --region-id MOH-52007 --data-file ../submodules/gig-data/geo/moh/MOH-52007.json
python manage.py insert_geo_data --type moh --name 'THIRUKKOVIL' --region-id MOH-52008 --data-file ../submodules/gig-data/geo/moh/MOH-52008.json
python manage.py insert_geo_data --type moh --name 'SAINTHAMARUTHU' --region-id MOH-52009 --data-file ../submodules/gig-data/geo/moh/MOH-52009.json
python manage.py insert_geo_data --type moh --name 'POTTUVIL' --region-id MOH-52010 --data-file ../submodules/gig-data/geo/moh/MOH-52010.json
python manage.py insert_geo_data --type moh --name 'NINTHAVUR' --region-id MOH-52011 --data-file ../submodules/gig-data/geo/moh/MOH-52011.json
python manage.py insert_geo_data --type moh --name 'NAVITHANVELI' --region-id MOH-52012 --data-file ../submodules/gig-data/geo/moh/MOH-52012.json
python manage.py insert_geo_data --type moh --name 'KARAITHIVU' --region-id MOH-52013 --data-file ../submodules/gig-data/geo/moh/MOH-52013.json
python manage.py insert_geo_data --type moh --name 'ARAYAMPATHY' --region-id MOH-51001 --data-file ../submodules/gig-data/geo/moh/MOH-51001.json
python manage.py insert_geo_data --type moh --name 'VALAICHENAI' --region-id MOH-51002 --data-file ../submodules/gig-data/geo/moh/MOH-51002.json
python manage.py insert_geo_data --type moh --name 'VELLAVELI' --region-id MOH-51003 --data-file ../submodules/gig-data/geo/moh/MOH-51003.json
python manage.py insert_geo_data --type moh --name 'VAVUNATHIVU' --region-id MOH-51004 --data-file ../submodules/gig-data/geo/moh/MOH-51004.json
python manage.py insert_geo_data --type moh --name 'VAKARAI' --region-id MOH-51005 --data-file ../submodules/gig-data/geo/moh/MOH-51005.json
python manage.py insert_geo_data --type moh --name 'CHENKALADY' --region-id MOH-51006 --data-file ../submodules/gig-data/geo/moh/MOH-51006.json
python manage.py insert_geo_data --type moh --name 'PADDIPALAI' --region-id MOH-51007 --data-file ../submodules/gig-data/geo/moh/MOH-51007.json
python manage.py insert_geo_data --type moh --name 'OTTAMAVADI' --region-id MOH-51008 --data-file ../submodules/gig-data/geo/moh/MOH-51008.json
python manage.py insert_geo_data --type moh --name 'KIRAN' --region-id MOH-51009 --data-file ../submodules/gig-data/geo/moh/MOH-51009.json
python manage.py insert_geo_data --type moh --name 'KORALAIPATTU ( ODDMAVADI CENTRAL )' --region-id MOH-51010 --data-file ../submodules/gig-data/geo/moh/MOH-51010.json
python manage.py insert_geo_data --type moh --name 'ERAVUR' --region-id MOH-51011 --data-file ../submodules/gig-data/geo/moh/MOH-51011.json
python manage.py insert_geo_data --type moh --name 'KATTANKUDY' --region-id MOH-51012 --data-file ../submodules/gig-data/geo/moh/MOH-51012.json
python manage.py insert_geo_data --type moh --name 'KALUWANCHIKUDY' --region-id MOH-51013 --data-file ../submodules/gig-data/geo/moh/MOH-51013.json
python manage.py insert_geo_data --type moh --name 'BATTICALOA' --region-id MOH-51014 --data-file ../submodules/gig-data/geo/moh/MOH-51014.json
python manage.py insert_geo_data --type moh --name 'KINNIYA' --region-id MOH-53001 --data-file ../submodules/gig-data/geo/moh/MOH-53001.json
python manage.py insert_geo_data --type moh --name 'KANTHALE' --region-id MOH-53002 --data-file ../submodules/gig-data/geo/moh/MOH-53002.json
python manage.py insert_geo_data --type moh --name 'KUCHCHAVELI' --region-id MOH-53003 --data-file ../submodules/gig-data/geo/moh/MOH-53003.json
python manage.py insert_geo_data --type moh --name 'MUTHUR' --region-id MOH-53004 --data-file ../submodules/gig-data/geo/moh/MOH-53004.json
python manage.py insert_geo_data --type moh --name 'PADAVI SRI PURA' --region-id MOH-53005 --data-file ../submodules/gig-data/geo/moh/MOH-53005.json
python manage.py insert_geo_data --type moh --name 'GOMARANKADAWALA' --region-id MOH-53006 --data-file ../submodules/gig-data/geo/moh/MOH-53006.json
python manage.py insert_geo_data --type moh --name 'SERUVILA' --region-id MOH-53007 --data-file ../submodules/gig-data/geo/moh/MOH-53007.json
python manage.py insert_geo_data --type moh --name 'THAMPALAGAMAM' --region-id MOH-53008 --data-file ../submodules/gig-data/geo/moh/MOH-53008.json
python manage.py insert_geo_data --type moh --name 'UPPUVELI' --region-id MOH-53009 --data-file ../submodules/gig-data/geo/moh/MOH-53009.json
python manage.py insert_geo_data --type moh --name 'TRINCOMALEE' --region-id MOH-53010 --data-file ../submodules/gig-data/geo/moh/MOH-53010.json
python manage.py insert_geo_data --type moh --name 'EACHCHILAMPATRU' --region-id MOH-53011 --data-file ../submodules/gig-data/geo/moh/MOH-53011.json
python manage.py insert_geo_data --type moh --name 'AMPARA' --region-id MOH-52014 --data-file ../submodules/gig-data/geo/moh/MOH-52014.json
python manage.py insert_geo_data --type moh --name 'DAMANA' --region-id MOH-52015 --data-file ../submodules/gig-data/geo/moh/MOH-52015.json
python manage.py insert_geo_data --type moh --name 'DEHIYATHAKANDIYA' --region-id MOH-52016 --data-file ../submodules/gig-data/geo/moh/MOH-52016.json
python manage.py insert_geo_data --type moh --name 'LAHUGALA' --region-id MOH-52017 --data-file ../submodules/gig-data/geo/moh/MOH-52017.json
python manage.py insert_geo_data --type moh --name 'MAHAOYA' --region-id MOH-52018 --data-file ../submodules/gig-data/geo/moh/MOH-52018.json
python manage.py insert_geo_data --type moh --name 'PADIYATHALAWA' --region-id MOH-52019 --data-file ../submodules/gig-data/geo/moh/MOH-52019.json
python manage.py insert_geo_data --type moh --name 'UHANA' --region-id MOH-52020 --data-file ../submodules/gig-data/geo/moh/MOH-52020.json
python manage.py insert_geo_data --type moh --name 'KAYTS' --region-id MOH-41001 --data-file ../submodules/gig-data/geo/moh/MOH-41001.json
python manage.py insert_geo_data --type moh --name 'CHAVAKACHCHERI' --region-id MOH-41002 --data-file ../submodules/gig-data/geo/moh/MOH-41002.json
python manage.py insert_geo_data --type moh --name 'NALLUR' --region-id MOH-41003 --data-file ../submodules/gig-data/geo/moh/MOH-41003.json
python manage.py insert_geo_data --type moh --name 'JAFFNA' --region-id MOH-41004 --data-file ../submodules/gig-data/geo/moh/MOH-41004.json
python manage.py insert_geo_data --type moh --name 'UDUVIL' --region-id MOH-41005 --data-file ../submodules/gig-data/geo/moh/MOH-41005.json
python manage.py insert_geo_data --type moh --name 'KOPAY' --region-id MOH-41006 --data-file ../submodules/gig-data/geo/moh/MOH-41006.json
python manage.py insert_geo_data --type moh --name 'POINT PEDRO' --region-id MOH-41007 --data-file ../submodules/gig-data/geo/moh/MOH-41007.json
python manage.py insert_geo_data --type moh --name 'TELLIPALAI' --region-id MOH-41008 --data-file ../submodules/gig-data/geo/moh/MOH-41008.json
python manage.py insert_geo_data --type moh --name 'SANDILIPAY' --region-id MOH-41009 --data-file ../submodules/gig-data/geo/moh/MOH-41009.json
python manage.py insert_geo_data --type moh --name 'CHANKANAI' --region-id MOH-41010 --data-file ../submodules/gig-data/geo/moh/MOH-41010.json
python manage.py insert_geo_data --type moh --name 'KARAVEDDY' --region-id MOH-41011 --data-file ../submodules/gig-data/geo/moh/MOH-41011.json
python manage.py insert_geo_data --type moh --name 'ODDUSUDDAN' --region-id MOH-44001 --data-file ../submodules/gig-data/geo/moh/MOH-44001.json
python manage.py insert_geo_data --type moh --name 'MANTHAI EAST' --region-id MOH-44002 --data-file ../submodules/gig-data/geo/moh/MOH-44002.json
python manage.py insert_geo_data --type moh --name 'MULLAITIVU' --region-id MOH-44003 --data-file ../submodules/gig-data/geo/moh/MOH-44003.json
python manage.py insert_geo_data --type moh --name 'PUTHUKKUDIYIRUPPU' --region-id MOH-44004 --data-file ../submodules/gig-data/geo/moh/MOH-44004.json
python manage.py insert_geo_data --type moh --name 'MALLAVI' --region-id MOH-44005 --data-file ../submodules/gig-data/geo/moh/MOH-44005.json
python manage.py insert_geo_data --type moh --name 'VAVUNIYA' --region-id MOH-43001 --data-file ../submodules/gig-data/geo/moh/MOH-43001.json
python manage.py insert_geo_data --type moh --name 'VAVUNIYA SOUTH' --region-id MOH-43002 --data-file ../submodules/gig-data/geo/moh/MOH-43002.json
python manage.py insert_geo_data --type moh --name 'WELIOYA' --region-id MOH-43003 --data-file ../submodules/gig-data/geo/moh/MOH-43003.json
python manage.py insert_geo_data --type moh --name 'CHEDDIKULAM' --region-id MOH-43004 --data-file ../submodules/gig-data/geo/moh/MOH-43004.json
python manage.py insert_geo_data --type moh --name 'VAVUNIYA NORTH' --region-id MOH-43005 --data-file ../submodules/gig-data/geo/moh/MOH-43005.json
python manage.py insert_geo_data --type moh --name 'NANATTAN' --region-id MOH-42001 --data-file ../submodules/gig-data/geo/moh/MOH-42001.json
python manage.py insert_geo_data --type moh --name 'MANNAR TOWN' --region-id MOH-42002 --data-file ../submodules/gig-data/geo/moh/MOH-42002.json
python manage.py insert_geo_data --type moh --name 'MANTHAI WEST' --region-id MOH-42003 --data-file ../submodules/gig-data/geo/moh/MOH-42003.json
python manage.py insert_geo_data --type moh --name 'MUSALAI' --region-id MOH-42004 --data-file ../submodules/gig-data/geo/moh/MOH-42004.json
python manage.py insert_geo_data --type moh --name 'MADHU' --region-id MOH-42005 --data-file ../submodules/gig-data/geo/moh/MOH-42005.json
python manage.py insert_geo_data --type moh --name 'KILINOCHCHI' --region-id MOH-45001 --data-file ../submodules/gig-data/geo/moh/MOH-45001.json
python manage.py insert_geo_data --type moh --name 'POONAKARY' --region-id MOH-45002 --data-file ../submodules/gig-data/geo/moh/MOH-45002.json
python manage.py insert_geo_data --type moh --name 'KANDAWALAI' --region-id MOH-45003 --data-file ../submodules/gig-data/geo/moh/MOH-45003.json
python manage.py insert_geo_data --type moh --name 'PALAI' --region-id MOH-45004 --data-file ../submodules/gig-data/geo/moh/MOH-45004.json
python manage.py insert_geo_data --type moh --name 'AYAGAMA' --region-id MOH-91001 --data-file ../submodules/gig-data/geo/moh/MOH-91001.json
python manage.py insert_geo_data --type moh --name 'BALANGODA' --region-id MOH-91002 --data-file ../submodules/gig-data/geo/moh/MOH-91002.json
python manage.py insert_geo_data --type moh --name 'EHELIYAGODA' --region-id MOH-91003 --data-file ../submodules/gig-data/geo/moh/MOH-91003.json
python manage.py insert_geo_data --type moh --name 'ELAPATHA' --region-id MOH-91004 --data-file ../submodules/gig-data/geo/moh/MOH-91004.json
python manage.py insert_geo_data --type moh --name 'EMBILIPITIYA' --region-id MOH-91005 --data-file ../submodules/gig-data/geo/moh/MOH-91005.json
python manage.py insert_geo_data --type moh --name 'GODAKAWELA' --region-id MOH-91006 --data-file ../submodules/gig-data/geo/moh/MOH-91006.json
python manage.py insert_geo_data --type moh --name 'IMBULPE' --region-id MOH-91007 --data-file ../submodules/gig-data/geo/moh/MOH-91007.json
python manage.py insert_geo_data --type moh --name 'KAHAWATHTHA' --region-id MOH-91008 --data-file ../submodules/gig-data/geo/moh/MOH-91008.json
python manage.py insert_geo_data --type moh --name 'KALAWANA' --region-id MOH-91009 --data-file ../submodules/gig-data/geo/moh/MOH-91009.json
python manage.py insert_geo_data --type moh --name 'KIRIELLA' --region-id MOH-91010 --data-file ../submodules/gig-data/geo/moh/MOH-91010.json
python manage.py insert_geo_data --type moh --name 'KOLONNA' --region-id MOH-91011 --data-file ../submodules/gig-data/geo/moh/MOH-91011.json
python manage.py insert_geo_data --type moh --name 'KURUWITA' --region-id MOH-91012 --data-file ../submodules/gig-data/geo/moh/MOH-91012.json
python manage.py insert_geo_data --type moh --name 'NIVITHIGALA' --region-id MOH-91013 --data-file ../submodules/gig-data/geo/moh/MOH-91013.json
python manage.py insert_geo_data --type moh --name 'OPANAYAKA' --region-id MOH-91014 --data-file ../submodules/gig-data/geo/moh/MOH-91014.json
python manage.py insert_geo_data --type moh --name 'PELMADULLA' --region-id MOH-91015 --data-file ../submodules/gig-data/geo/moh/MOH-91015.json
python manage.py insert_geo_data --type moh --name 'RATNAPURA-MC' --region-id MOH-91016 --data-file ../submodules/gig-data/geo/moh/MOH-91016.json
python manage.py insert_geo_data --type moh --name 'RATNAPURA' --region-id MOH-91017 --data-file ../submodules/gig-data/geo/moh/MOH-91017.json
python manage.py insert_geo_data --type moh --name 'WELIGEPOLA' --region-id MOH-91018 --data-file ../submodules/gig-data/geo/moh/MOH-91018.json
python manage.py insert_geo_data --type moh --name 'DIMBULAGALA' --region-id MOH-72001 --data-file ../submodules/gig-data/geo/moh/MOH-72001.json
python manage.py insert_geo_data --type moh --name 'ELAHERA' --region-id MOH-72002 --data-file ../submodules/gig-data/geo/moh/MOH-72002.json
python manage.py insert_geo_data --type moh --name 'HINGURAKGODA' --region-id MOH-72003 --data-file ../submodules/gig-data/geo/moh/MOH-72003.json
python manage.py insert_geo_data --type moh --name 'LANKAPURA' --region-id MOH-72004 --data-file ../submodules/gig-data/geo/moh/MOH-72004.json
python manage.py insert_geo_data --type moh --name 'MEDIRIGIRIYA' --region-id MOH-72005 --data-file ../submodules/gig-data/geo/moh/MOH-72005.json
python manage.py insert_geo_data --type moh --name 'THAMANKADUWA' --region-id MOH-72006 --data-file ../submodules/gig-data/geo/moh/MOH-72006.json
python manage.py insert_geo_data --type moh --name 'WELIKANDA' --region-id MOH-72007 --data-file ../submodules/gig-data/geo/moh/MOH-72007.json
python manage.py insert_geo_data --type moh --name 'ARANAYAKA' --region-id MOH-92001 --data-file ../submodules/gig-data/geo/moh/MOH-92001.json
python manage.py insert_geo_data --type moh --name 'BULATHKOHUPITIYA' --region-id MOH-92002 --data-file ../submodules/gig-data/geo/moh/MOH-92002.json
python manage.py insert_geo_data --type moh --name 'DEHIOVITA' --region-id MOH-92003 --data-file ../submodules/gig-data/geo/moh/MOH-92003.json
python manage.py insert_geo_data --type moh --name 'DERANIYAGALA' --region-id MOH-92004 --data-file ../submodules/gig-data/geo/moh/MOH-92004.json
python manage.py insert_geo_data --type moh --name 'GALIGAMUWA' --region-id MOH-92005 --data-file ../submodules/gig-data/geo/moh/MOH-92005.json
python manage.py insert_geo_data --type moh --name 'KEGALLE' --region-id MOH-92006 --data-file ../submodules/gig-data/geo/moh/MOH-92006.json
python manage.py insert_geo_data --type moh --name 'MAWANELLA' --region-id MOH-92007 --data-file ../submodules/gig-data/geo/moh/MOH-92007.json
python manage.py insert_geo_data --type moh --name 'RAMBUKKANA' --region-id MOH-92008 --data-file ../submodules/gig-data/geo/moh/MOH-92008.json
python manage.py insert_geo_data --type moh --name 'RUWANWELLA' --region-id MOH-92009 --data-file ../submodules/gig-data/geo/moh/MOH-92009.json
python manage.py insert_geo_data --type moh --name 'WARAKAPOLA' --region-id MOH-92010 --data-file ../submodules/gig-data/geo/moh/MOH-92010.json
python manage.py insert_geo_data --type moh --name 'YATIYANTHOTA' --region-id MOH-92011 --data-file ../submodules/gig-data/geo/moh/MOH-92011.json
python manage.py insert_geo_data --type moh --name 'Welimada' --region-id MOH-81001 --data-file ../submodules/gig-data/geo/moh/MOH-81001.json
python manage.py insert_geo_data --type moh --name 'Rideemaliyadda' --region-id MOH-81002 --data-file ../submodules/gig-data/geo/moh/MOH-81002.json
python manage.py insert_geo_data --type moh --name 'Uva Paranagama' --region-id MOH-81003 --data-file ../submodules/gig-data/geo/moh/MOH-81003.json
python manage.py insert_geo_data --type moh --name 'Haliela' --region-id MOH-81004 --data-file ../submodules/gig-data/geo/moh/MOH-81004.json
python manage.py insert_geo_data --type moh --name 'Mahiyanganaya' --region-id MOH-81005 --data-file ../submodules/gig-data/geo/moh/MOH-81005.json
python manage.py insert_geo_data --type moh --name 'Lunugala' --region-id MOH-81006 --data-file ../submodules/gig-data/geo/moh/MOH-81006.json
python manage.py insert_geo_data --type moh --name 'Haputhale' --region-id MOH-81007 --data-file ../submodules/gig-data/geo/moh/MOH-81007.json
python manage.py insert_geo_data --type moh --name 'Badulla' --region-id MOH-81008 --data-file ../submodules/gig-data/geo/moh/MOH-81008.json
python manage.py insert_geo_data --type moh --name 'Soranathota' --region-id MOH-81009 --data-file ../submodules/gig-data/geo/moh/MOH-81009.json
python manage.py insert_geo_data --type moh --name 'Haldummulla' --region-id MOH-81010 --data-file ../submodules/gig-data/geo/moh/MOH-81010.json
python manage.py insert_geo_data --type moh --name 'Kandaketiya' --region-id MOH-81011 --data-file ../submodules/gig-data/geo/moh/MOH-81011.json
python manage.py insert_geo_data --type moh --name 'Girandurukotte' --region-id MOH-81012 --data-file ../submodules/gig-data/geo/moh/MOH-81012.json
python manage.py insert_geo_data --type moh --name 'Ella' --region-id MOH-81013 --data-file ../submodules/gig-data/geo/moh/MOH-81013.json
python manage.py insert_geo_data --type moh --name 'Meegahakivula' --region-id MOH-81014 --data-file ../submodules/gig-data/geo/moh/MOH-81014.json
python manage.py insert_geo_data --type moh --name 'Bandarawela' --region-id MOH-81015 --data-file ../submodules/gig-data/geo/moh/MOH-81015.json
python manage.py insert_geo_data --type moh --name 'Passara' --region-id MOH-81016 --data-file ../submodules/gig-data/geo/moh/MOH-81016.json
python manage.py insert_geo_data --type moh --name 'HOROWPOTHANA' --region-id MOH-71001 --data-file ../submodules/gig-data/geo/moh/MOH-71001.json
python manage.py insert_geo_data --type moh --name 'NUWARAGAM PALATHA CENTRAL' --region-id MOH-71002 --data-file ../submodules/gig-data/geo/moh/MOH-71002.json
python manage.py insert_geo_data --type moh --name 'IPALOGAMA' --region-id MOH-71003 --data-file ../submodules/gig-data/geo/moh/MOH-71003.json
python manage.py insert_geo_data --type moh --name 'KAHATAGASDIGILIYA' --region-id MOH-71004 --data-file ../submodules/gig-data/geo/moh/MOH-71004.json
python manage.py insert_geo_data --type moh --name 'NUWARAGAM PALATHA EAST' --region-id MOH-71005 --data-file ../submodules/gig-data/geo/moh/MOH-71005.json
python manage.py insert_geo_data --type moh --name 'KEBITHIGOLLEWA' --region-id MOH-71006 --data-file ../submodules/gig-data/geo/moh/MOH-71006.json
python manage.py insert_geo_data --type moh --name 'THIRAPPANE' --region-id MOH-71007 --data-file ../submodules/gig-data/geo/moh/MOH-71007.json
python manage.py insert_geo_data --type moh --name 'PADAVIYA' --region-id MOH-71008 --data-file ../submodules/gig-data/geo/moh/MOH-71008.json
python manage.py insert_geo_data --type moh --name 'GALENBIDUNUWAWE' --region-id MOH-71009 --data-file ../submodules/gig-data/geo/moh/MOH-71009.json
python manage.py insert_geo_data --type moh --name 'MEDAWACHCHIYA' --region-id MOH-71010 --data-file ../submodules/gig-data/geo/moh/MOH-71010.json
python manage.py insert_geo_data --type moh --name 'KEKIRAWA' --region-id MOH-71011 --data-file ../submodules/gig-data/geo/moh/MOH-71011.json
python manage.py insert_geo_data --type moh --name 'THAMBUTTEGAMA' --region-id MOH-71012 --data-file ../submodules/gig-data/geo/moh/MOH-71012.json
python manage.py insert_geo_data --type moh --name 'GALNEWA' --region-id MOH-71013 --data-file ../submodules/gig-data/geo/moh/MOH-71013.json
python manage.py insert_geo_data --type moh --name 'MIHINTALE' --region-id MOH-71014 --data-file ../submodules/gig-data/geo/moh/MOH-71014.json
python manage.py insert_geo_data --type moh --name 'RAMBEWA' --region-id MOH-71015 --data-file ../submodules/gig-data/geo/moh/MOH-71015.json
python manage.py insert_geo_data --type moh --name 'THALAWA' --region-id MOH-71016 --data-file ../submodules/gig-data/geo/moh/MOH-71016.json
python manage.py insert_geo_data --type moh --name 'NOCHCHIYAGAMA' --region-id MOH-71017 --data-file ../submodules/gig-data/geo/moh/MOH-71017.json
python manage.py insert_geo_data --type moh --name 'PALAGALA' --region-id MOH-71018 --data-file ../submodules/gig-data/geo/moh/MOH-71018.json
python manage.py insert_geo_data --type moh --name 'RAJANGANAYA' --region-id MOH-71019 --data-file ../submodules/gig-data/geo/moh/MOH-71019.json
python manage.py insert_geo_data --type moh --name 'Galgamuwa' --region-id MOH-61001 --data-file ../submodules/gig-data/geo/moh/MOH-61001.json
python manage.py insert_geo_data --type moh --name 'Ambanpola' --region-id MOH-61002 --data-file ../submodules/gig-data/geo/moh/MOH-61002.json
python manage.py insert_geo_data --type moh --name 'Ganewatta' --region-id MOH-61003 --data-file ../submodules/gig-data/geo/moh/MOH-61003.json
python manage.py insert_geo_data --type moh --name 'Mahawa' --region-id MOH-61004 --data-file ../submodules/gig-data/geo/moh/MOH-61004.json
python manage.py insert_geo_data --type moh --name 'Kurunegala' --region-id MOH-61005 --data-file ../submodules/gig-data/geo/moh/MOH-61005.json
python manage.py insert_geo_data --type moh --name 'Panduwasnuwara' --region-id MOH-61006 --data-file ../submodules/gig-data/geo/moh/MOH-61006.json
python manage.py insert_geo_data --type moh --name 'Kobeigane' --region-id MOH-61007 --data-file ../submodules/gig-data/geo/moh/MOH-61007.json
python manage.py insert_geo_data --type moh --name 'Giribawa' --region-id MOH-61008 --data-file ../submodules/gig-data/geo/moh/MOH-61008.json
python manage.py insert_geo_data --type moh --name 'Polgahawela' --region-id MOH-61009 --data-file ../submodules/gig-data/geo/moh/MOH-61009.json
python manage.py insert_geo_data --type moh --name 'Udubaddawa' --region-id MOH-61010 --data-file ../submodules/gig-data/geo/moh/MOH-61010.json
python manage.py insert_geo_data --type moh --name 'Wariyapola' --region-id MOH-61011 --data-file ../submodules/gig-data/geo/moh/MOH-61011.json
python manage.py insert_geo_data --type moh --name 'Pannala' --region-id MOH-61012 --data-file ../submodules/gig-data/geo/moh/MOH-61012.json
python manage.py insert_geo_data --type moh --name 'Mawathagama' --region-id MOH-61013 --data-file ../submodules/gig-data/geo/moh/MOH-61013.json
python manage.py insert_geo_data --type moh --name 'Rideegama' --region-id MOH-61014 --data-file ../submodules/gig-data/geo/moh/MOH-61014.json
python manage.py insert_geo_data --type moh --name 'Bamunukotuwa' --region-id MOH-61015 --data-file ../submodules/gig-data/geo/moh/MOH-61015.json
python manage.py insert_geo_data --type moh --name 'Bingiriya' --region-id MOH-61016 --data-file ../submodules/gig-data/geo/moh/MOH-61016.json
python manage.py insert_geo_data --type moh --name 'Polpithigama' --region-id MOH-61017 --data-file ../submodules/gig-data/geo/moh/MOH-61017.json
python manage.py insert_geo_data --type moh --name 'ALAWWA' --region-id MOH-61018 --data-file ../submodules/gig-data/geo/moh/MOH-61018.json
python manage.py insert_geo_data --type moh --name 'Katupotha' --region-id MOH-61019 --data-file ../submodules/gig-data/geo/moh/MOH-61019.json
python manage.py insert_geo_data --type moh --name 'Kotawehera' --region-id MOH-61020 --data-file ../submodules/gig-data/geo/moh/MOH-61020.json
python manage.py insert_geo_data --type moh --name 'Ibbagamuwa' --region-id MOH-61021 --data-file ../submodules/gig-data/geo/moh/MOH-61021.json
python manage.py insert_geo_data --type moh --name 'Narammala' --region-id MOH-61022 --data-file ../submodules/gig-data/geo/moh/MOH-61022.json
python manage.py insert_geo_data --type moh --name 'Mallawapitiya' --region-id MOH-61023 --data-file ../submodules/gig-data/geo/moh/MOH-61023.json
python manage.py insert_geo_data --type moh --name 'Maspotha' --region-id MOH-61024 --data-file ../submodules/gig-data/geo/moh/MOH-61024.json
python manage.py insert_geo_data --type moh --name 'Kuliyapitiya' --region-id MOH-61025 --data-file ../submodules/gig-data/geo/moh/MOH-61025.json
python manage.py insert_geo_data --type moh --name 'Nikaweratiya' --region-id MOH-61026 --data-file ../submodules/gig-data/geo/moh/MOH-61026.json
python manage.py insert_geo_data --type moh --name 'Weerambugedara' --region-id MOH-61027 --data-file ../submodules/gig-data/geo/moh/MOH-61027.json
python manage.py insert_geo_data --type moh --name 'Thanamalwila' --region-id MOH-82001 --data-file ../submodules/gig-data/geo/moh/MOH-82001.json
python manage.py insert_geo_data --type moh --name 'Monaragala' --region-id MOH-82002 --data-file ../submodules/gig-data/geo/moh/MOH-82002.json
python manage.py insert_geo_data --type moh --name 'Bibila' --region-id MOH-82003 --data-file ../submodules/gig-data/geo/moh/MOH-82003.json
python manage.py insert_geo_data --type moh --name 'Wellawaya' --region-id MOH-82004 --data-file ../submodules/gig-data/geo/moh/MOH-82004.json
python manage.py insert_geo_data --type moh --name 'Buttala' --region-id MOH-82005 --data-file ../submodules/gig-data/geo/moh/MOH-82005.json
python manage.py insert_geo_data --type moh --name 'Siyambalanduwa' --region-id MOH-82006 --data-file ../submodules/gig-data/geo/moh/MOH-82006.json
python manage.py insert_geo_data --type moh --name 'Kataragama' --region-id MOH-82007 --data-file ../submodules/gig-data/geo/moh/MOH-82007.json
python manage.py insert_geo_data --type moh --name 'Badalkumbura' --region-id MOH-82008 --data-file ../submodules/gig-data/geo/moh/MOH-82008.json
python manage.py insert_geo_data --type moh --name 'Sevanagala' --region-id MOH-82009 --data-file ../submodules/gig-data/geo/moh/MOH-82009.json
python manage.py insert_geo_data --type moh --name 'Madulla' --region-id MOH-82010 --data-file ../submodules/gig-data/geo/moh/MOH-82010.json
python manage.py insert_geo_data --type moh --name 'Mundalama' --region-id MOH-62001 --data-file ../submodules/gig-data/geo/moh/MOH-62001.json
python manage.py insert_geo_data --type moh --name 'Anamaduwa' --region-id MOH-62002 --data-file ../submodules/gig-data/geo/moh/MOH-62002.json
python manage.py insert_geo_data --type moh --name 'Chilaw' --region-id MOH-62003 --data-file ../submodules/gig-data/geo/moh/MOH-62003.json
python manage.py insert_geo_data --type moh --name 'Dankotuwa' --region-id MOH-62004 --data-file ../submodules/gig-data/geo/moh/MOH-62004.json
python manage.py insert_geo_data --type moh --name 'Karuwalagaswewa' --region-id MOH-62005 --data-file ../submodules/gig-data/geo/moh/MOH-62005.json
python manage.py insert_geo_data --type moh --name 'Wennappuwa' --region-id MOH-62006 --data-file ../submodules/gig-data/geo/moh/MOH-62006.json
python manage.py insert_geo_data --type moh --name 'Arachchikattuwa' --region-id MOH-62007 --data-file ../submodules/gig-data/geo/moh/MOH-62007.json
python manage.py insert_geo_data --type moh --name 'Nattandiya' --region-id MOH-62008 --data-file ../submodules/gig-data/geo/moh/MOH-62008.json
python manage.py insert_geo_data --type moh --name 'Puttalam' --region-id MOH-62009 --data-file ../submodules/gig-data/geo/moh/MOH-62009.json
python manage.py insert_geo_data --type moh --name 'Kalpitiya' --region-id MOH-62010 --data-file ../submodules/gig-data/geo/moh/MOH-62010.json
python manage.py insert_geo_data --type moh --name 'Mahawewa' --region-id MOH-62011 --data-file ../submodules/gig-data/geo/moh/MOH-62011.json
python manage.py insert_geo_data --type moh --name 'Pallama' --region-id MOH-62012 --data-file ../submodules/gig-data/geo/moh/MOH-62012.json
python manage.py insert_geo_data --type moh --name 'BATTARAMULLA' --region-id MOH-11001 --data-file ../submodules/gig-data/geo/moh/MOH-11001.json
python manage.py insert_geo_data --type moh --name 'BORALESGAMUWA' --region-id MOH-11002 --data-file ../submodules/gig-data/geo/moh/MOH-11002.json
python manage.py insert_geo_data --type moh --name 'CMC' --region-id MOH-11003 --data-file ../submodules/gig-data/geo/moh/MOH-11003.json
python manage.py insert_geo_data --type moh --name 'DEHIWALA' --region-id MOH-11004 --data-file ../submodules/gig-data/geo/moh/MOH-11004.json
python manage.py insert_geo_data --type moh --name 'HANWELLA' --region-id MOH-11005 --data-file ../submodules/gig-data/geo/moh/MOH-11005.json
python manage.py insert_geo_data --type moh --name 'HOMAGAMA' --region-id MOH-11006 --data-file ../submodules/gig-data/geo/moh/MOH-11006.json
python manage.py insert_geo_data --type moh --name 'KADUWELA' --region-id MOH-11007 --data-file ../submodules/gig-data/geo/moh/MOH-11007.json
python manage.py insert_geo_data --type moh --name 'KAHATHUDUWA' --region-id MOH-11008 --data-file ../submodules/gig-data/geo/moh/MOH-11008.json
python manage.py insert_geo_data --type moh --name 'KOLONNAWA' --region-id MOH-11009 --data-file ../submodules/gig-data/geo/moh/MOH-11009.json
python manage.py insert_geo_data --type moh --name 'MAHARAGAMA' --region-id MOH-11010 --data-file ../submodules/gig-data/geo/moh/MOH-11010.json
python manage.py insert_geo_data --type moh --name 'MORATUWA' --region-id MOH-11011 --data-file ../submodules/gig-data/geo/moh/MOH-11011.json
python manage.py insert_geo_data --type moh --name 'NUGEGODA' --region-id MOH-11012 --data-file ../submodules/gig-data/geo/moh/MOH-11012.json
python manage.py insert_geo_data --type moh --name 'PADUKKA' --region-id MOH-11013 --data-file ../submodules/gig-data/geo/moh/MOH-11013.json
python manage.py insert_geo_data --type moh --name 'PILIYANDALA' --region-id MOH-11014 --data-file ../submodules/gig-data/geo/moh/MOH-11014.json
python manage.py insert_geo_data --type moh --name 'PITAKOTTE' --region-id MOH-11015 --data-file ../submodules/gig-data/geo/moh/MOH-11015.json
python manage.py insert_geo_data --type moh --name 'RATHMALANA' --region-id MOH-11016 --data-file ../submodules/gig-data/geo/moh/MOH-11016.json
python manage.py insert_geo_data --type moh --name 'AGALAWATTA' --region-id MOH-13001 --data-file ../submodules/gig-data/geo/moh/MOH-13001.json
python manage.py insert_geo_data --type moh --name 'BANDARAGAMA' --region-id MOH-13002 --data-file ../submodules/gig-data/geo/moh/MOH-13002.json
python manage.py insert_geo_data --type moh --name 'BERUWALA' --region-id MOH-13003 --data-file ../submodules/gig-data/geo/moh/MOH-13003.json
python manage.py insert_geo_data --type moh --name 'BULATHSINHALA' --region-id MOH-13004 --data-file ../submodules/gig-data/geo/moh/MOH-13004.json
python manage.py insert_geo_data --type moh --name 'HORANA' --region-id MOH-13005 --data-file ../submodules/gig-data/geo/moh/MOH-13005.json
python manage.py insert_geo_data --type moh --name 'INGIRIYA' --region-id MOH-13006 --data-file ../submodules/gig-data/geo/moh/MOH-13006.json
python manage.py insert_geo_data --type moh --name 'KALUTARA' --region-id MOH-13007 --data-file ../submodules/gig-data/geo/moh/MOH-13007.json
python manage.py insert_geo_data --type moh --name 'MADURAWALA' --region-id MOH-13008 --data-file ../submodules/gig-data/geo/moh/MOH-13008.json
python manage.py insert_geo_data --type moh --name 'MATHUGAMA' --region-id MOH-13009 --data-file ../submodules/gig-data/geo/moh/MOH-13009.json
python manage.py insert_geo_data --type moh --name 'PALINDANUWARA' --region-id MOH-13010 --data-file ../submodules/gig-data/geo/moh/MOH-13010.json
python manage.py insert_geo_data --type moh --name 'PANADURA' --region-id MOH-13011 --data-file ../submodules/gig-data/geo/moh/MOH-13011.json
python manage.py insert_geo_data --type moh --name 'WALALLAWITA' --region-id MOH-13012 --data-file ../submodules/gig-data/geo/moh/MOH-13012.json
python manage.py insert_geo_data --type moh --name 'ATTANAGALLA' --region-id MOH-12001 --data-file ../submodules/gig-data/geo/moh/MOH-12001.json
python manage.py insert_geo_data --type moh --name 'BIYAGAMA' --region-id MOH-12002 --data-file ../submodules/gig-data/geo/moh/MOH-12002.json
python manage.py insert_geo_data --type moh --name 'DIVULAPITIYA' --region-id MOH-12003 --data-file ../submodules/gig-data/geo/moh/MOH-12003.json
python manage.py insert_geo_data --type moh --name 'DOMPE' --region-id MOH-12004 --data-file ../submodules/gig-data/geo/moh/MOH-12004.json
python manage.py insert_geo_data --type moh --name 'GAMPAHA' --region-id MOH-12005 --data-file ../submodules/gig-data/geo/moh/MOH-12005.json
python manage.py insert_geo_data --type moh --name 'JA-ELA' --region-id MOH-12006 --data-file ../submodules/gig-data/geo/moh/MOH-12006.json
python manage.py insert_geo_data --type moh --name 'KATANA' --region-id MOH-12007 --data-file ../submodules/gig-data/geo/moh/MOH-12007.json
python manage.py insert_geo_data --type moh --name 'KELANIYA' --region-id MOH-12008 --data-file ../submodules/gig-data/geo/moh/MOH-12008.json
python manage.py insert_geo_data --type moh --name 'MAHARA' --region-id MOH-12009 --data-file ../submodules/gig-data/geo/moh/MOH-12009.json
python manage.py insert_geo_data --type moh --name 'MINUWANGODA' --region-id MOH-12010 --data-file ../submodules/gig-data/geo/moh/MOH-12010.json
python manage.py insert_geo_data --type moh --name 'MIRIGAMA' --region-id MOH-12011 --data-file ../submodules/gig-data/geo/moh/MOH-12011.json
python manage.py insert_geo_data --type moh --name 'NEGAMBO' --region-id MOH-12012 --data-file ../submodules/gig-data/geo/moh/MOH-12012.json
python manage.py insert_geo_data --type moh --name 'RAGAMA' --region-id MOH-12013 --data-file ../submodules/gig-data/geo/moh/MOH-12013.json
python manage.py insert_geo_data --type moh --name 'SEEDUWA' --region-id MOH-12014 --data-file ../submodules/gig-data/geo/moh/MOH-12014.json
python manage.py insert_geo_data --type moh --name 'WATTALA' --region-id MOH-12015 --data-file ../submodules/gig-data/geo/moh/MOH-12015.json
