# Generated by Django 4.2.19 on 2025-02-18 06:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0002_geopolygon_region_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopolygon',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
