# Generated by Django 4.2.19 on 2025-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0003_alter_geopolygon_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topology",
            fields=[
                (
                    "region_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=20)),
                ("topology_data", models.JSONField()),
            ],
            options={
                "db_table": "topology",
                "indexes": [
                    models.Index(fields=["type"], name="topology_type_95d154_idx")
                ],
            },
        ),
    ]
