# Generated by Django 4.2.19 on 2025-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_app", "0004_topology"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topology",
            options={"verbose_name_plural": "topologies"},
        ),
        migrations.RemoveIndex(
            model_name="topology",
            name="topology_type_95d154_idx",
        ),
        migrations.RenameField(
            model_name="topology",
            old_name="topology_data",
            new_name="arcs",
        ),
        migrations.AddField(
            model_name="topology",
            name="geometry_type",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topology",
            name="properties",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="topology",
            table=None,
        ),
    ]
